import { useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Calendar, Users, Bot, CheckCircle2, TrendingUp, Sparkles, ArrowUpRight } from "lucide-react"
import { Bar, BarChart, ResponsiveContainer, XAxis, YAxis, Tooltip } from "recharts"
import { jwtDecode } from "jwt-decode"
import { useNavigate } from "react-router-dom"
import { useQuery } from "@tanstack/react-query"
import { meetingsApi } from "@/services/meetings.api"
import { AnimatedPage } from "@/components/layout/AnimatedPage"

export function Overview() {
  const navigate = useNavigate()
  
  const [role, setRole] = useState(() => {
    const token = localStorage.getItem("token")
    if (token) {
      try {
        const decoded = jwtDecode(token)
        return decoded.role || "GUEST"
      } catch (e) {}
    }
    return "GUEST"
  })
  
  const isOrgAdmin = role === "SUPER_ADMIN" || role === "ORG_ADMIN"

  const { data: analyticsData } = useQuery({
    queryKey: ['analytics'],
    queryFn: meetingsApi.getAnalytics,
  })

  const stats = analyticsData?.data || {
    totalMeetings: 0,
    completedMeetings: 0,
    upcomingMeetings: 0,
    meetingsWithSummaries: 0,
    monthlyData: [
      { name: "Jan", total: 0 },
      { name: "Feb", total: 0 },
      { name: "Mar", total: 0 },
      { name: "Apr", total: 0 },
      { name: "May", total: 0 },
      { name: "Jun", total: 0 },
    ]
  }

  const statCards = [
    {
      title: "Total Meetings",
      value: stats.totalMeetings,
      subtitle: "All time across workspace",
      icon: Calendar,
      gradient: "from-blue-500 to-cyan-500",
      bgGlow: "bg-blue-500/10",
      iconColor: "text-blue-400",
    },
    {
      title: "Upcoming",
      value: stats.upcomingMeetings,
      subtitle: "Scheduled and waiting",
      icon: TrendingUp,
      gradient: "from-violet-500 to-purple-500",
      bgGlow: "bg-violet-500/10",
      iconColor: "text-violet-400",
    },
    {
      title: "Completed",
      value: stats.completedMeetings,
      subtitle: "Successfully finished",
      icon: CheckCircle2,
      gradient: "from-emerald-500 to-green-500",
      bgGlow: "bg-emerald-500/10",
      iconColor: "text-emerald-400",
    },
    {
      title: "AI Summaries",
      value: stats.meetingsWithSummaries,
      subtitle: "Generated by Gemini",
      icon: Sparkles,
      gradient: "from-amber-500 to-orange-500",
      bgGlow: "bg-amber-500/10",
      iconColor: "text-amber-400",
    },
  ]

  return (
    <AnimatedPage>
      <div className="space-y-8 max-w-7xl mx-auto pb-10">
        {/* Page Header */}
      <div className="flex flex-col gap-1">
        <h1 className="text-3xl font-bold tracking-tight text-white">Dashboard</h1>
        <p className="text-slate-400">
          Here's an overview of your schedule and AI usage.
        </p>
      </div>

      <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">
        {statCards.map((card, i) => (
          <Card key={i} className="relative overflow-hidden border-white/5 bg-white/[0.03] backdrop-blur-sm hover:bg-white/[0.06] transition-all duration-300 group">
            <div className={`absolute top-0 right-0 w-32 h-32 ${card.bgGlow} rounded-full -translate-y-1/2 translate-x-1/2 blur-2xl opacity-60 group-hover:opacity-100 transition-opacity`} />
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-3 relative">
              <CardTitle className="text-sm font-medium text-slate-400">{card.title}</CardTitle>
              <div className={`flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br ${card.gradient} shadow-lg`}>
                <card.icon className="h-4 w-4 text-white" />
              </div>
            </CardHeader>
            <CardContent className="relative">
              <div className="text-3xl font-bold text-white">{card.value}</div>
              <p className="text-xs text-slate-500 mt-1 flex items-center gap-1">
                {card.subtitle}
              </p>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Quick Actions */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        <Card className="border-white/5 bg-gradient-to-br from-blue-500/10 to-indigo-500/10 hover:from-blue-500/20 hover:to-indigo-500/20 transition-all cursor-pointer" onClick={() => navigate('/dashboard/meetings')}>
          <CardContent className="p-6 flex items-center gap-4">
            <div className="h-12 w-12 rounded-full bg-blue-500/20 flex items-center justify-center">
              <Users className="h-6 w-6 text-blue-400" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-white">Manage Meetings</h3>
              <p className="text-sm text-slate-400">View schedule and create new meetings</p>
            </div>
          </CardContent>
        </Card>
        
        <Card className="border-white/5 bg-gradient-to-br from-emerald-500/10 to-teal-500/10 hover:from-emerald-500/20 hover:to-teal-500/20 transition-all cursor-pointer" onClick={() => navigate('/dashboard/documents')}>
          <CardContent className="p-6 flex items-center gap-4">
            <div className="h-12 w-12 rounded-full bg-emerald-500/20 flex items-center justify-center">
              <Bot className="h-6 w-6 text-emerald-400" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-white">AI Knowledge Base</h3>
              <p className="text-sm text-slate-400">Upload documents for AI to learn from</p>
            </div>
          </CardContent>
        </Card>

        {isOrgAdmin && (
          <Card className="border-white/5 bg-gradient-to-br from-purple-500/10 to-pink-500/10 hover:from-purple-500/20 hover:to-pink-500/20 transition-all cursor-pointer" onClick={() => navigate('/dashboard/organization')}>
            <CardContent className="p-6 flex items-center gap-4">
              <div className="h-12 w-12 rounded-full bg-purple-500/20 flex items-center justify-center">
                <Sparkles className="h-6 w-6 text-purple-400" />
              </div>
              <div>
                <h3 className="text-lg font-bold text-white">Workspace Members</h3>
                <p className="text-sm text-slate-400">Invite team members and manage roles</p>
              </div>
            </CardContent>
          </Card>
        )}
      </div>

      {/* Charts Row */}
      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-7">
        {/* Meeting Volume Chart */}
        <Card className="col-span-4 border-white/5 bg-white/[0.03] backdrop-blur-sm">
          <CardHeader className="pb-2">
            <div className="flex items-center justify-between">
              <div>
                <CardTitle className="text-white text-lg">Meeting Volume</CardTitle>
                <CardDescription className="text-slate-500">Monthly meeting trends</CardDescription>
              </div>
              <div className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-blue-500/10 text-xs font-semibold text-blue-400">
                <TrendingUp className="h-3.5 w-3.5" /> Trending
              </div>
            </div>
          </CardHeader>
          <CardContent className="pl-2 pt-4">
            <ResponsiveContainer width="100%" height={320}>
              <BarChart data={stats.monthlyData}>
                <XAxis
                  dataKey="name"
                  stroke="#475569"
                  fontSize={12}
                  tickLine={false}
                  axisLine={false}
                />
                <YAxis
                  stroke="#475569"
                  fontSize={12}
                  tickLine={false}
                  axisLine={false}
                  tickFormatter={(value) => `${value}`}
                />
                <Tooltip 
                  cursor={{fill: 'rgba(255, 255, 255, 0.03)'}} 
                  contentStyle={{ backgroundColor: '#1e293b', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', color: '#fff', boxShadow: '0 25px 50px -12px rgba(0,0,0,0.5)' }}
                  labelStyle={{ color: '#94a3b8', marginBottom: 4 }}
                />
                <Bar dataKey="total" fill="url(#blueGradient)" radius={[6, 6, 0, 0]} />
                <defs>
                  <linearGradient id="blueGradient" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor="#3b82f6" stopOpacity={1}/>
                    <stop offset="100%" stopColor="#6366f1" stopOpacity={0.8}/>
                  </linearGradient>
                </defs>
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        {/* System Status (Admin Only) */}
        {(role === "SUPER_ADMIN" || role === "ORG_ADMIN") && (
        <Card className="col-span-3 border-white/5 bg-white/[0.03] backdrop-blur-sm">
          <CardHeader>
            <CardTitle className="text-white text-lg">System Status</CardTitle>
            <CardDescription className="text-slate-500">
              Microservices health monitor
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-5">
              {[
                { title: "API Gateway", status: "Online", port: 8000, color: "emerald" },
                { title: "Auth Service", status: "Online", port: 8001, color: "emerald" },
                { title: "Meeting Service", status: "Online", port: 8002, color: "emerald" },
                { title: "AI Service", status: "Online", port: 8003, color: "blue" },
                { title: "Email Service", status: "Online", port: 8004, color: "emerald" },
              ].map((service, i) => (
                <div key={i} className="flex items-center justify-between p-3 rounded-xl bg-white/[0.03] border border-white/5 hover:bg-white/[0.06] transition-all">
                  <div className="space-y-0.5">
                    <p className="text-sm font-semibold text-white">{service.title}</p>
                    <p className="text-[11px] text-slate-500 font-mono">
                      :{service.port}
                    </p>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="relative flex h-2 w-2">
                      <span className={`animate-ping absolute inline-flex h-full w-full rounded-full bg-${service.color}-400 opacity-75`}></span>
                      <span className={`relative inline-flex rounded-full h-2 w-2 bg-${service.color}-500`}></span>
                    </span>
                    <span className={`text-xs font-semibold text-${service.color}-400`}>{service.status}</span>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
        )}
      </div>
      </div>
    </AnimatedPage>
  )
}
